FROM python:3.7-alpine

WORKDIR /app


# RUN apk add --no-cache gcc musl-dev linux-headers geos libc-dev postgresql-dev
RUN apk add --no-cache gcc g++ musl-dev linux-headers libc-dev libpq-dev python-dev
COPY requirements.txt /
RUN pip install -r /requirements.txt


COPY ./app /app
RUN python -m grpc_tools.protoc -I./ --python_out=./ --grpc_python_out=./ person.proto

#CMD ["python", "main.py"]

#COPY . .
#CMD ["flask", "run", "--host", "0.0.0.0"]