kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: udaconnect-postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi