apiVersion: v1
kind: Service
metadata:
  labels:
    service: person-service
  name: person-service
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    protocol: TCP
    # nodePort: 30015
  selector:
    service: person-service
  # type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: person-service
  name: person-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: person-service
  template:
    metadata:
      labels:
        service: person-service
    spec:
      containers:
      - image: leoadams/udaconnect-person-service:latest
        name: person-service
        ports:
        - containerPort: 5005
          protocol: TCP
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      #restartPolicy: Always
