apiVersion: v1
kind: Service
metadata:
  labels:
    service: person-api-v2
  name: person-api-v2
spec:
  ports:
  - name: "5009"
    port: 5009
    targetPort: 5000
    protocol: TCP
    nodePort: 30009
  selector:
    service: person-api-v2
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: person-api-v2
  name: person-api-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      service: person-api-v2
  template:
    metadata:
      labels:
        service: person-api-v2
    spec:
      containers:
      - image: leoadams/udaconnect-person-api-v2:latest
        name: person-api-v2
        #imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      #restartPolicy: Always
