apiVersion: v1
kind: Service
metadata:
  labels:
    service: person-api
  name: person-api
spec:
  ports:
  - name: "5004"
    port: 5004
    targetPort: 5000
    protocol: TCP
    nodePort: 30014
  selector:
    service: person-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: person-api
  name: person-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: person-api
  template:
    metadata:
      labels:
        service: person-api
    spec:
      containers:
      - image: leoadams/udaconnect-person-api:latest
        name: person-api
        imagePullPolicy: IfNotPresent
        #imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      #restartPolicy: Always
