kind: PersistentVolume
apiVersion: v1
metadata:
  name: udaconnect-postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 260Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"