FROM python:3.7-alpine

WORKDIR /app


# RUN apk add --no-cache gcc musl-dev linux-headers geos libc-dev postgresql-dev
RUN apk add --no-cache gcc g++ musl-dev linux-headers libc-dev libpq-dev
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
#RUN apk add protobuf

# ENV PROTOC_ZIP=protoc-3.15.8-linux-x86_64.zip
# RUN curl -OL https://github.com/google/protobuf/releases/download/v3.15.8/$PROTOC_ZIP
# RUN unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
# RUN unzip -o $PROTOC_ZIP -d /usr/local include/*
# RUN rm -f $PROTOC_ZIP


COPY ./app .
#RUN python -m grpc_tools.protoc -I./ --python_out=./ --grpc_python_out=./ person.proto

# COPY main.py /

ENV DB_PASSWORD=secret
ENV DB_NAME=geoconnections
ENV DB_HOST=postgres
ENV DB_PORT=5432
ENV DB_USERNAME=ct_admin

EXPOSE 5005

ENTRYPOINT ["python", "main.py"]
#CMD ["python", "main.py"]

#COPY . .
#CMD ["flask", "run", "--host", "0.0.0.0"]